// <auto-generated />
using System;
using IdentityManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IdentityManager.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260602000000_InitialIdentity")]
partial class InitialIdentity
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 63)
            .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

        modelBuilder.Entity("IdentityManager.Models.ApplicationUser", b =>
        {
            b.Property<string>("Id").HasColumnType("text");
            b.Property<int>("AccessFailedCount").HasColumnType("integer");
            b.Property<string>("ConcurrencyStamp").HasColumnType("text");
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("Email").HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<bool>("EmailConfirmed").HasColumnType("boolean");
            b.Property<string>("FirstName").IsRequired().HasColumnType("text");
            b.Property<bool>("IsActive").HasColumnType("boolean");
            b.Property<string>("LastName").IsRequired().HasColumnType("text");
            b.Property<bool>("LockoutEnabled").HasColumnType("boolean");
            b.Property<DateTimeOffset?>("LockoutEnd").HasColumnType("timestamp with time zone");
            b.Property<string>("NormalizedEmail").HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<string>("NormalizedUserName").HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<string>("PasswordHash").HasColumnType("text");
            b.Property<string>("PhoneNumber").HasColumnType("text");
            b.Property<bool>("PhoneNumberConfirmed").HasColumnType("boolean");
            b.Property<string>("SecurityStamp").HasColumnType("text");
            b.Property<bool>("TwoFactorEnabled").HasColumnType("boolean");
            b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("UserName").HasMaxLength(256).HasColumnType("character varying(256)");
            b.HasKey("Id");
            b.HasIndex("NormalizedEmail").HasDatabaseName("EmailIndex");
            b.HasIndex("NormalizedUserName").IsUnique().HasDatabaseName("UserNameIndex");
            b.ToTable("AspNetUsers", (string)null);
        });

        modelBuilder.Entity("IdentityManager.Models.RefreshToken", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<DateTime>("ExpiresAt").HasColumnType("timestamp with time zone");
            b.Property<bool>("IsRevoked").HasColumnType("boolean");
            b.Property<string>("Token").IsRequired().HasColumnType("text");
            b.Property<string>("UserId").IsRequired().HasColumnType("text");
            b.HasKey("Id");
            b.HasIndex("Token").IsUnique();
            b.HasIndex("UserId");
            b.ToTable("RefreshTokens");
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
        {
            b.Property<string>("Id").HasColumnType("text");
            b.Property<string>("ConcurrencyStamp").HasColumnType("text");
            b.Property<string>("Name").HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<string>("NormalizedName").HasMaxLength(256).HasColumnType("character varying(256)");
            b.HasKey("Id");
            b.HasIndex("NormalizedName").IsUnique().HasDatabaseName("RoleNameIndex");
            b.ToTable("AspNetRoles", (string)null);
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            b.Property<string>("ClaimType").HasColumnType("text");
            b.Property<string>("ClaimValue").HasColumnType("text");
            b.Property<string>("RoleId").IsRequired().HasColumnType("text");
            b.HasKey("Id");
            b.HasIndex("RoleId");
            b.ToTable("AspNetRoleClaims", (string)null);
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            b.Property<string>("ClaimType").HasColumnType("text");
            b.Property<string>("ClaimValue").HasColumnType("text");
            b.Property<string>("UserId").IsRequired().HasColumnType("text");
            b.HasKey("Id");
            b.HasIndex("UserId");
            b.ToTable("AspNetUserClaims", (string)null);
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
        {
            b.Property<string>("LoginProvider").HasColumnType("text");
            b.Property<string>("ProviderKey").HasColumnType("text");
            b.Property<string>("ProviderDisplayName").HasColumnType("text");
            b.Property<string>("UserId").IsRequired().HasColumnType("text");
            b.HasKey("LoginProvider", "ProviderKey");
            b.HasIndex("UserId");
            b.ToTable("AspNetUserLogins", (string)null);
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
        {
            b.Property<string>("UserId").HasColumnType("text");
            b.Property<string>("RoleId").HasColumnType("text");
            b.HasKey("UserId", "RoleId");
            b.HasIndex("RoleId");
            b.ToTable("AspNetUserRoles", (string)null);
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
        {
            b.Property<string>("UserId").HasColumnType("text");
            b.Property<string>("LoginProvider").HasColumnType("text");
            b.Property<string>("Name").HasColumnType("text");
            b.Property<string>("Value").HasColumnType("text");
            b.HasKey("UserId", "LoginProvider", "Name");
            b.ToTable("AspNetUserTokens", (string)null);
        });

        modelBuilder.Entity("IdentityManager.Models.RefreshToken", b =>
        {
            b.HasOne("IdentityManager.Models.ApplicationUser", "User")
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("User");
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
        {
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                .WithMany()
                .HasForeignKey("RoleId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
        {
            b.HasOne("IdentityManager.Models.ApplicationUser", null)
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
        {
            b.HasOne("IdentityManager.Models.ApplicationUser", null)
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
        {
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                .WithMany()
                .HasForeignKey("RoleId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.HasOne("IdentityManager.Models.ApplicationUser", null)
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
        {
            b.HasOne("IdentityManager.Models.ApplicationUser", null)
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });
#pragma warning restore 612, 618
    }
}
